---
title: "**S632 - Final Project Proposal**"
author: "**Gokcen Buyukbas, Adnan Cihan Cakar**"
date: "4/14/2021"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

<style type="text/css">
  body{ /* Normal  */
      font-size: 11px;
  }
td {  /* Table  */
  font-size: 10px;
}
h1.title {
  font-size: 18px;
  color: DarkRed;
}
h1.author {
  font-size: 16px;
  color: DarkRed;
}
h1 { /* Header 1 */
  font-size: 14px;
  color: DarkBlue;
}
h2 { /* Header 2 */
  font-size: 13px;
  color: DarkBlue;
}
h3 { /* Header 3 */
  font-size: 12px;
  color: DarkBlue;
}
code.r{ /* Code block */
    font-size: 10px;
}

.col2 {
    columns: 2 200px;         /* number of columns and width in pixels*/
    -webkit-columns: 2 200px; /* chrome, safari */
    -moz-columns: 2 200px;    /* firefox */
  }
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE,
               cache=TRUE, autodep=TRUE, cache.comments=FALSE,
               message=FALSE, warning=FALSE)
```

## **Reasearch Question:** 
What song features play a significant role in a song's popularity?

## **Plan:**
1. Model selection, variable selection

## **Description of the data**
The data consists of 174389 songs with 19 features described below. 

### **Primary:**
* id (Id of track generated by Spotify)

### **Numerical variables:**
<div class="col2">
* acousticness (Ranges from 0 to 1)
* danceability (Ranges from 0 to 1)
* energy (Ranges from 0 to 1)
* duration_ms (Integer typically ranging from 200k to 300k)
* instrumentalness (Ranges from 0 to 1)
* valence (Ranges from 0 to 1)
* popularity (Ranges from 0 to 100)
* tempo (Float typically ranging from 50 to 150)
* liveness (Ranges from 0 to 1)
* loudness (Float typically ranging from -60 to 0)
* speechiness (Ranges from 0 to 1)
* year (Ranges from 1921 to 2020)
</div>

### **Categorical variables:**
* mode (0 = Minor, 1 = Major)
* explicit (0 = No explicit content, 1 = Explicit content)
* key (All keys on octave encoded as values ranging from 0 to 11, starting on C as 0, C# as 1 and so on…)
* artists (List of artists mentioned)
* release_date (Date of release mostly in yyyy-mm-dd format, however precision of date may vary)
* name (Name of the song)

## **Data processing:**
* Removed the id, artists and name of tracks
* Created a new categorical variable, *season*, based on the release date, and removed the variable release_date  
* Converted the categorical variables to factor
* Created a binary response, pop_binary, from popularity; 0 if popularity$<50$, 1 otherwise.

## **Methods:**