---
title: "S632 - Final Project - Spotify Tracks"
author: "Adnan Cihan Cakar, Gokcen Buyukbas"
date: "4/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Import

```{r}
tracks = read.csv("C:/Users/aciha/Google Drive/curwordir/S632/final_project/spofity/data.csv")
```

```{r}
year_cut = 2015
tracks = tracks[tracks$year>2015,]
tracks = subset(tracks, select=-c("id","artists"))

tracks$release_date = as.Date(tracks$release_date)

getSeason <- function(date) {
    WS <- as.Date("2012-12-15", format = "%Y-%m-%d") # Winter Solstice
    SE <- as.Date("2012-3-15",  format = "%Y-%m-%d") # Spring Equinox
    SS <- as.Date("2012-6-15",  format = "%Y-%m-%d") # Summer Solstice
    FE <- as.Date("2012-9-15",  format = "%Y-%m-%d") # Fall Equinox

    # Convert dates from any year to 2012 dates
    d <- as.Date(strftime(date, format="2012-%m-%d"))

    ifelse (d >= WS | d < SE, "Winter",
      ifelse (d >= SE & d < SS, "Spring",
        ifelse (d >= SS & d < FE, "Summer", "Fall")))
}
tracks$season = apply(as.data.frame(tracks$release_date), 1, getSeason)
```


```{r}
model = glm(popularity ~ .,family = binomial, tracks)
```


